# Generated by Django 2.2.5 on 2019-09-19 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20190919_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreboardmodel',
            name='game_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
